---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: lindluni@github.com
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - selector:
          dnsZones:
            - "es.github.expert-services.io"
            - "kibana.github.expert-services.io"
        dns01:
          route53:
            region: us-east-1
            accessKeyID: <placeholder>
            secretAccessKeySecretRef:
              name: route53-credentials
              key: secret-access-key
