---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: insights
  namespace: default
spec:
  selector:
    matchLabels:
      app: insights
  replicas: 1
  template:
    metadata:
      labels:
        app: insights
    spec:
      containers:
        - name: insights
          image: ghcr.io/oss-tooling/github-metrics:es-beta-0.0.10
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: GH_INSIGHTS_HOST
              value: "quickstart-es-http.default.svc.cluster.local"
            - name: GH_INSIGHTS_USERNAME
              value: elastic
            - name: GH_INSIGHTS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: quickstart-es-elastic-user
                  key: elastic
                  optional: false
            - name: GH_INSIGHTS_CA_CERT
              valueFrom:
                secretKeyRef:
                  name: quickstart-es-http-ca-internal
                  key: tls.crt
                  optional: false
            - name: GH_INSIGHTS_WEBHOOK_SECRET
              valueFrom:
                secretKeyRef:
                  name: insights-app
                  key: webhook_secret
                  optional: false
      imagePullSecrets:
        - name: ghcr
